name: simple_coverflow
description: An extremely simplistic "cover flow" style animation to swipe between widgets.
version: 0.0.3
author: Emily Fortuna <efortuna@google.com>
homepage: https://github.com/efortuna/coverflow

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=1.19.0 <2.1.0'
  flutter: '>=0.1.0 <0.3.0'